package Test_Cases;

import java.io.IOException;

import org.testng.annotations.Test;

public class TC_003 {
	@Test(groups = {"Datadriven"})
	public void entrytest() throws IOException
	{
		System.out.println("This is third test case and the message is ");
		System.out.println("This is third test case and the message is ");
		System.out.println("This is third test case and the message is ");
		System.out.println("This is third test case and the message is ");
	}

}
